name: Appium CI
# on push we will trigger our code
on: [push]



jobs:
  build:
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28] 
        target: [default]
    steps:
    - uses: actions/checkout@v2 #checkout the code 
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone repository
      run: git clone git@github.com:dev3fyfy/github_actions_test.git
    - name: Files
      run: ls -laR github_actions_test
    - name: Install and Run Appium Server
      run: |
        chmod +x ./script/RunAppiumServer.sh # install and run appium server in the background
        ./script/RunAppiumServer.sh
        chmod +x ./gradlew
        cd github_actions_test
        ls
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        working-directory: github_actions_test
        script: ./gradlew test --info # running our test with info to check the results
  
