name: Android CI - Build and Publish APK

on:
  workflow_dispatch:
    inputs:
      message:
        required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 9.*
#       - name: Build APK - test
#         run: bash ./gradlew build --stacktrace 

#         # display file apk path
#       - name: Files
#         run: ls -laR app/build/outputs/apk/*
#       - name: upload artifact to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1
#         with:
#           appId: ${{secrets.FIREBASE_APP_ID}}
#           token: ${{secrets.FIREBASE_TOKEN}}
#           groups: testers
#           releaseNotes: "aaaaa"
#           file: app/build/outputs/apk/debug/app-debug.apk
      - name: run
        run: |
          touch txt.txt
          
      - name: Send APK to Slack - test
        uses: adrey/slack-file-upload-action@master
        continue-on-error: true
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_CHANNELS }}
          path: 'txt.txt'
          filename: 'txt.txt'
          filetype: 'txt'
          initial_comment: "${{ github.ref }} - \n  ${{github.event.inputs.message}}    5 \n   11 \n 111     "
      - name: Notify slack success
        if: success()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'success'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Notify slack fail
        if: failure()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
