 name: Example

 on:
   push:
     branches:
        - master
 # pull_request:

 jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2
      - name: show resume.tex file content
        run: cat app/build.gradle
      - name: find version name
        run: |
          grep -r "versionName"  app/build.gradle
          $Version_Name = grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' 


      - run: git tag $Version_Name
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #exclude: true
          #draft: true
          template: '{commits}'
      - name: Update major tag
        run: |
          MAJOR=$Version_Name
          git push origin HEAD:refs/tags/$MAJOR --force


