name: Production Build and Publish APK - Production

on:
  workflow_dispatch:
    inputs:
      production_release:
        description: 'Select type'
        required: true
        default: 'mobile Full' 
        type: choice
        options:
        - mobile Full
        - mobile Lite
        - Pax Full
        - Pax Lite
        - Sunumi Full
        - Sunumi Lite      
jobs:
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/checkout@v2
