 name: Example

 on:
   push:
     branches:
        - master
 # pull_request:
 

 jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v1
      - name: show resume.tex file content
        run: cat app/build.gradle
      - name: find version name
        run: |
          grep -r "versionName"  app/build.gradle
          grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' 


      - run: git tag $( grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' )
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #exclude: true
          #draft: true
          template: '{commits}'
 #     - name: Update major tag
  #      run: |
   #       MAJOR=$( grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' )
    #      git push origin HEAD:refs/tags/$MAJOR --force
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: FAILED
          color: danger

