 name: Status

 on:
   push:
     branches:
        - master
 # pull_request:
 

 jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v1

      - name: show resume.tex file content
        run: cat app/build.gradle
      - name: find version name
        run: |
          grep -r "versionName"  app/build.gradle
          grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' 


      - run: git tag $( grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' )
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #exclude: true
          #draft: true
          template: '{commits}'
 #     - name: Update major tag
  #      run: |
   #       MAJOR=$( grep -r "versionName"  app/build.gradle |awk -F '"' '{print $2}' )
    #      git push origin HEAD:refs/tags/$MAJOR --force
      - name: Notify slack success
        if: success()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'success'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Notify slack fail
        if: failure()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

