
name:  Push tag & Create release

on:
  push:
    branches:
      - master   
jobs:
   
   
  build:
    name: build APK
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                                  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: find version name
        run: |
          grep -r "versionName"  tools/gradle/base.gradle |echo "v"$(awk -F '"' '{print $2}')
           echo "TAG=4.00.0" >> $GITHUB_ENV
      - name: Create new Tag 
        run: git tag ${{ env.TAG }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name:  ${{ env.TAG }}
          release_name:  ${{ env.TAG }}
          body: |
             ${{ steps.Changelog.outputs.changelog }}
             
          draft: false
          prerelease: false

